### ISSUE TITLE
PRs that need to be merged into master

### ISSUE THREAD

**Issue by valueof** [jshint/jshint#1579]
- [x] Strip comments in JSON by parsing instead of regex (#1567)
- [ ] Reporting correct column for JavaScript extracted from HTML files (#1557)
- [ ] Don't throw an error when yield statement used within a catch block inside a generator function (#1543)
- [ ] Glob documentation for example .jshintignore (#1553)
- [x] Switch statement within loop doesn't recognize 'continue' if case is wra... (#1548)
- [ ] Support a --filename flag (#1503)
